# ===== H2 Database =====
spring.datasource.url=jdbc:h2:mem:posdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== Server =====
server.port=8088

# ===== Business Config =====
pos.tax.rate=0.19
pos.frozen.expiry-minutes=120

# ===== OpenAPI / Swagger =====
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===== Scheduling =====
spring.main.allow-bean-definition-overriding=true
